version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "ea:26:4e:2a:5a:93:5d:93:5a:f5:39:1c:9c:01:c5:00"
      - run: bash deploy.bash
